apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-mailhog
  template:
    metadata:
      labels:
        app: django-mailhog
    spec:
      containers:
      - name: django-mailhog
        image: 40781998/django-mailhog:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 8000

        env:
          - name: EMAIL_HOST
            valueFrom: 
              configMapKeyRef:
                name: mailhog-config
                key: EMAIL_HOST

          - name: EMAIL_PORT
            valueFrom: 
              configMapKeyRef:
                name: mailhog-config
                key: EMAIL_PORT

          - name: EMAIL_HOST_USER
            valueFrom: 
              configMapKeyRef:
                name: mailhog-config
                key: EMAIL_HOST_USER

          - name: EMAIL_HOST_PASSWORD
            valueFrom: 
              configMapKeyRef:
                name: mailhog-config
                key: EMAIL_HOST_PASSWORD

          - name: EMAIL_USE_TLS
            valueFrom: 
              configMapKeyRef:
                name: mailhog-config
                key: EMAIL_USE_TLS